export const SET_SEARCHED_ITEM = 'SET_SEARCHED_ITEM';
export const SET_ERROR = 'SET_ERROR';
export const SET_FIRST_RESULTS = 'SET_FIRST_RESULTS';
export const SET_RESULTS = 'SET_RESULTS';
export const SET_LOADING = 'SET_LOADING';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
